package gui;

import com.intellij.uiDesigner.core.GridLayoutManager;
import entities.HocSinh;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.Locale;

public class GiaoDienMenuHocSinh extends JPanel {
    private HocSinh hocSinh;
    private JPanel panel1;
    private JPanel panelCaiDatTaiKhoan;
    private JPanel panelDanhSachBaiThi;
    private JPanel panelNoiDung;
    private JLabel lbTenHocSinh;
    private JLabel lbDangXuat;
    private JLabel lbTaiKhoan;
    private JLabel lbXemKetQua; // Thêm nhãn mới cho Xem kết quả
    private JPanel pnDangXuat;

    public GiaoDienMenuHocSinh(HocSinh hocSinh) {
        this.hocSinh = hocSinh;
        $$$setupUI$$$();
        lbTenHocSinh.setText(hocSinh.getHoTen());
        lbDangXuat.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int confirm = JOptionPane.showConfirmDialog(null,
                        "Bạn có chắc chắn muốn đăng xuất?",
                        "Xác nhận đăng xuất",
                        JOptionPane.YES_NO_OPTION);
                if (confirm == JOptionPane.YES_OPTION) {
                    // Đóng cửa sổ hiện tại (GiaoDienChinh) và mở lại GiaoDienDangNhap
                    SwingUtilities.getWindowAncestor(panel1).dispose(); // Đóng cửa sổ hiện tại

                    JFrame frame = new JFrame("Đăng Nhập");
                    frame.setContentPane(new GiaoDienDangNhap().$$$getRootComponent$$$());
                    frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                    frame.pack();
                    frame.setLocationRelativeTo(null);
                    frame.setVisible(true);
                }
            }
        });
        lbTaiKhoan.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                panelNoiDung.removeAll();
                panelNoiDung.add(new GiaoDienCaiDatTaiKhoan().$$$getRootComponent$$$());
                panelNoiDung.revalidate();
                panelNoiDung.repaint();
            }
        });
        lbXemKetQua.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                panelNoiDung.removeAll();
                panelNoiDung.add(new GiaoDienHocSinhXemKetQua().$$$getRootComponent$$$());
                panelNoiDung.revalidate();
                panelNoiDung.repaint();
            }
        });
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new BorderLayout(0, 0));
        panel2.setBackground(new Color(-6106369));
        panel2.setPreferredSize(new Dimension(200, 20));
        panel1.add(panel2, BorderLayout.WEST);
        lbTenHocSinh = new JLabel();
        lbTenHocSinh.setBackground(new Color(-6106369));
        lbTenHocSinh.setHorizontalAlignment(0);
        lbTenHocSinh.setHorizontalTextPosition(0);
        lbTenHocSinh.setPreferredSize(new Dimension(200, 50));
        lbTenHocSinh.setText("Label");
        panel2.add(lbTenHocSinh, BorderLayout.NORTH);
        lbDangXuat = new JLabel();
        lbDangXuat.setHorizontalAlignment(0);
        lbDangXuat.setPreferredSize(new Dimension(71, 30));
        lbDangXuat.setText("Đăng xuất");
        panel2.add(lbDangXuat, BorderLayout.SOUTH);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panel3.setBackground(new Color(-6106369));
        panel2.add(panel3, BorderLayout.CENTER);
        final JLabel label1 = new JLabel();
        label1.setBackground(new Color(-4333314));
        label1.setHorizontalAlignment(0);
        label1.setOpaque(true);
        label1.setPreferredSize(new Dimension(200, 30));
        label1.setText("Danh sách bài thi");
        panel3.add(label1);
        lbTaiKhoan = new JLabel();
        lbTaiKhoan.setBackground(new Color(-4333314));
        lbTaiKhoan.setHorizontalAlignment(0);
        lbTaiKhoan.setOpaque(true);
        lbTaiKhoan.setPreferredSize(new Dimension(200, 30));
        lbTaiKhoan.setText("Tài khoản");
        panel3.add(lbTaiKhoan);
        lbXemKetQua = new JLabel();
        lbXemKetQua.setBackground(new Color(-4333314));
        lbXemKetQua.setHorizontalAlignment(0);
        lbXemKetQua.setOpaque(true);
        lbXemKetQua.setPreferredSize(new Dimension(200, 30));
        lbXemKetQua.setText("Xem kết quả");
        panel3.add(lbXemKetQua);
        panelNoiDung = new JPanel();
        panelNoiDung.setLayout(new BorderLayout(0, 0));
        panel1.add(panelNoiDung, BorderLayout.CENTER);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
    }
}