package gui;

import entities.GiaoVien;

import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

public class GiaoDienMenuGiaoVien {
    private GiaoVien giaoVien;
    private JPanel panel1;
    private JPanel panelNoiDung;
    private JLabel lbTenGiaoVien;
    private JLabel lbNganHangCauHoi;
    private JLabel lbDSDeThi;
    private JLabel lbLopHocTap;
    private JLabel lbCaiDatTaiKhoan;
    private JLabel lbDangXuat;


    public GiaoDienMenuGiaoVien(GiaoVien giaoVien) {
        this.giaoVien = giaoVien;
        $$$setupUI$$$();
        lbTenGiaoVien.setText(giaoVien.getHoTen());
        lbCaiDatTaiKhoan.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                panelNoiDung.removeAll();
                panelNoiDung.add(new GiaoDienCaiDatTaiKhoan().$$$getRootComponent$$$());
                panelNoiDung.revalidate();
                panelNoiDung.repaint();
            }
        });
        lbDangXuat.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int confirm = JOptionPane.showConfirmDialog(null,
                        "Bạn có chắc chắn muốn đăng xuất?",
                        "Xác nhận đăng xuất",
                        JOptionPane.YES_NO_OPTION);
                if (confirm == JOptionPane.YES_OPTION) {
                    // Đóng cửa sổ hiện tại (GiaoDienChinh) và mở lại GiaoDienDangNhap
                    SwingUtilities.getWindowAncestor(panel1).dispose(); // Đóng cửa sổ hiện tại

                    JFrame frame = new JFrame("Đăng Nhập");
                    frame.setContentPane(new GiaoDienDangNhap().$$$getRootComponent$$$());
                    frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                    frame.pack();
                    frame.setLocationRelativeTo(null);
                    frame.setVisible(true);
                }
            }
        });
    }

//    {
//// GUI initializer generated by IntelliJ IDEA GUI Designer
//// >>> IMPORTANT!! <<<
//// DO NOT EDIT OR ADD ANY CODE HERE!
//        $$$setupUI$$$();
//    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new BorderLayout(0, 0));
        panel2.setBackground(new Color(-6106369));
        panel2.setPreferredSize(new Dimension(200, 10));
        panel1.add(panel2, BorderLayout.WEST);
        lbTenGiaoVien = new JLabel();
        lbTenGiaoVien.setBackground(new Color(-6106369));
        lbTenGiaoVien.setHorizontalAlignment(0);
        lbTenGiaoVien.setHorizontalTextPosition(0);
        lbTenGiaoVien.setPreferredSize(new Dimension(200, 50));
        lbTenGiaoVien.setText("Tên giáo viên");
        panel2.add(lbTenGiaoVien, BorderLayout.NORTH);
        lbDangXuat = new JLabel();
        lbDangXuat.setAlignmentX(0.5f);
        lbDangXuat.setHorizontalAlignment(0);
        lbDangXuat.setHorizontalTextPosition(0);
        lbDangXuat.setPreferredSize(new Dimension(71, 30));
        lbDangXuat.setText("Đăng xuất");
        panel2.add(lbDangXuat, BorderLayout.SOUTH);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panel3.setBackground(new Color(-6106369));
        panel2.add(panel3, BorderLayout.CENTER);
        lbNganHangCauHoi = new JLabel();
        lbNganHangCauHoi.setBackground(new Color(-4333314));
        lbNganHangCauHoi.setHorizontalAlignment(0);
        lbNganHangCauHoi.setHorizontalTextPosition(0);
        lbNganHangCauHoi.setOpaque(true);
        lbNganHangCauHoi.setPreferredSize(new Dimension(200, 30));
        lbNganHangCauHoi.setText("Ngân hàng câu hỏi");
        panel3.add(lbNganHangCauHoi);
        lbDSDeThi = new JLabel();
        lbDSDeThi.setBackground(new Color(-4333314));
        lbDSDeThi.setHorizontalAlignment(0);
        lbDSDeThi.setHorizontalTextPosition(0);
        lbDSDeThi.setOpaque(true);
        lbDSDeThi.setPreferredSize(new Dimension(200, 30));
        lbDSDeThi.setText("Danh sách đề thi");
        panel3.add(lbDSDeThi);
        lbLopHocTap = new JLabel();
        lbLopHocTap.setBackground(new Color(-4333314));
        lbLopHocTap.setHorizontalAlignment(0);
        lbLopHocTap.setHorizontalTextPosition(0);
        lbLopHocTap.setOpaque(true);
        lbLopHocTap.setPreferredSize(new Dimension(200, 30));
        lbLopHocTap.setText("Lớp học tập");
        panel3.add(lbLopHocTap);
        lbCaiDatTaiKhoan = new JLabel();
        lbCaiDatTaiKhoan.setBackground(new Color(-4333314));
        lbCaiDatTaiKhoan.setHorizontalAlignment(0);
        lbCaiDatTaiKhoan.setHorizontalTextPosition(0);
        lbCaiDatTaiKhoan.setOpaque(true);
        lbCaiDatTaiKhoan.setPreferredSize(new Dimension(200, 30));
        lbCaiDatTaiKhoan.setText("Tài khoản");
        panel3.add(lbCaiDatTaiKhoan);
        panelNoiDung = new JPanel();
        panelNoiDung.setLayout(new BorderLayout(0, 0));
        panel1.add(panelNoiDung, BorderLayout.CENTER);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

}
