package gui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import entities.GiaoVien;
import entities.HocSinh;
import entities.TaiKhoan;
import service.GiaoVienService;
import service.HocSinhService;
import service.TaiKhoanService;

import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.net.MalformedURLException;
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;

public class GiaoDienCaiDatTaiKhoan extends JPanel {
    private JPanel panel1;
    private JButton btnTTTK;
    private JButton btnDMK;
    private JPanel panelNoiDungCaiDat;
    private JPanel panelChucNang;
    private JPanel panelTTTK;
    private JPanel panelDMK;
    private JTextField txtSDT;
    private JTextField txtHoTen;
    private JTextField txtEmail;
    private JButton lưuButton;
    private JTextField txtVaiTro;
    private JLabel lbLop;
    private JTextField txtLop;
    private GiaoVienService giaoVienService = (GiaoVienService) Naming.lookup("rmi://localhost:8081/giaoVienService");

    public GiaoDienCaiDatTaiKhoan(TaiKhoan taiKhoan) throws MalformedURLException, NotBoundException, RemoteException {
        $$$setupUI$$$();
        txtVaiTro.setText(taiKhoan.getLoaiTaiKhoan());
        if (taiKhoan.getLoaiTaiKhoan().equalsIgnoreCase("GiaoVien")) {
            GiaoVien giaoVien = giaoVienService.timGiaoVienTheoEmail(taiKhoan.getTenDangNhap());
            txtHoTen.setText(giaoVien.getHoTen());
            txtEmail.setText(giaoVien.getEmail());
            txtSDT.setText(giaoVien.getSoDienThoai());
            panelTTTK.remove(lbLop);
            panelTTTK.remove(txtLop);
        }
        if (taiKhoan.getLoaiTaiKhoan().equalsIgnoreCase("HocSinh")) {
            HocSinhService hocSinhService = (HocSinhService) Naming.lookup("rmi://localhost:8081/hocSinhService");
            HocSinh hocSinh = hocSinhService.timHocSinhTheoEmail(taiKhoan.getTenDangNhap());
            txtHoTen.setText(hocSinh.getHoTen());
            txtEmail.setText(hocSinh.getEmail());
            txtSDT.setText(hocSinh.getSoDienThoai());
            txtLop.setText(hocSinh.getLop().getTenLop());
        }
        btnTTTK.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                panelNoiDungCaiDat.removeAll();
                panelNoiDungCaiDat.add(panelTTTK);
                panelNoiDungCaiDat.repaint();
                panelNoiDungCaiDat.revalidate();
            }
        });

        btnDMK.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                panelNoiDungCaiDat.removeAll();
                panelNoiDungCaiDat.add(panelDMK);
                panelNoiDungCaiDat.repaint();
                panelNoiDungCaiDat.revalidate();
            }
        });
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        panelChucNang = new JPanel();
        panelChucNang.setLayout(new BorderLayout(0, 0));
        panelChucNang.setBackground(new Color(-1));
        panelChucNang.setMaximumSize(new Dimension(200, 200));
        panelChucNang.setPreferredSize(new Dimension(200, 103));
        panel1.add(panelChucNang, BorderLayout.WEST);
        final JLabel label1 = new JLabel();
        label1.setAlignmentX(0.5f);
        label1.setHorizontalAlignment(0);
        label1.setPreferredSize(new Dimension(117, 50));
        label1.setText("Cài đặt tài khoản");
        panelChucNang.add(label1, BorderLayout.NORTH);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panel2.setBackground(new Color(-1));
        panelChucNang.add(panel2, BorderLayout.CENTER);
        btnTTTK = new JButton();
        btnTTTK.setPreferredSize(new Dimension(180, 43));
        btnTTTK.setText("Thông tin tài khoản");
        panel2.add(btnTTTK);
        btnDMK = new JButton();
        btnDMK.setMaximumSize(new Dimension(180, 43));
        btnDMK.setPreferredSize(new Dimension(180, 43));
        btnDMK.setText("Đổi mật khẩu");
        panel2.add(btnDMK);
        panelNoiDungCaiDat = new JPanel();
        panelNoiDungCaiDat.setLayout(new CardLayout(0, 0));
        panel1.add(panelNoiDungCaiDat, BorderLayout.CENTER);
        panelTTTK = new JPanel();
        panelTTTK.setLayout(new GridLayoutManager(7, 3, new Insets(10, 10, 10, 10), 2, 2));
        panelTTTK.setBackground(new Color(-1));
        panelNoiDungCaiDat.add(panelTTTK, "Card1");
        final JLabel label2 = new JLabel();
        label2.setBackground(new Color(-368076));
        label2.setText("Họ tên");
        panelTTTK.add(label2, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(30, 10), null, 0, false));
        final Spacer spacer1 = new Spacer();
        panelTTTK.add(spacer1, new GridConstraints(2, 2, 3, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final JLabel label3 = new JLabel();
        label3.setText("Email");
        panelTTTK.add(label3, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label4 = new JLabel();
        label4.setText("Số điện thoại");
        panelTTTK.add(label4, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtSDT = new JTextField();
        txtSDT.setDisabledTextColor(new Color(-16777216));
        txtSDT.setEditable(false);
        txtSDT.setEnabled(false);
        txtSDT.setSelectionColor(new Color(-16777216));
        txtSDT.setText("0123456789");
        panelTTTK.add(txtSDT, new GridConstraints(4, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        txtEmail = new JTextField();
        txtEmail.setDisabledTextColor(new Color(-16777216));
        txtEmail.setEditable(false);
        txtEmail.setEnabled(false);
        txtEmail.setSelectionColor(new Color(-16777216));
        txtEmail.setText("a@gmail.com");
        panelTTTK.add(txtEmail, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        txtHoTen = new JTextField();
        txtHoTen.setDisabledTextColor(new Color(-16777216));
        txtHoTen.setEditable(false);
        txtHoTen.setEnabled(false);
        txtHoTen.setSelectionColor(new Color(-16777216));
        txtHoTen.setText("Nguyễn Văn A");
        panelTTTK.add(txtHoTen, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        lưuButton = new JButton();
        lưuButton.setText("Lưu");
        panelTTTK.add(lưuButton, new GridConstraints(6, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label5 = new JLabel();
        label5.setBackground(new Color(-368076));
        label5.setText("Vai trò");
        panelTTTK.add(label5, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(30, 10), null, 0, false));
        txtVaiTro = new JTextField();
        txtVaiTro.setDisabledTextColor(new Color(-16777216));
        txtVaiTro.setEditable(false);
        txtVaiTro.setEnabled(false);
        txtVaiTro.setSelectionColor(new Color(-16777216));
        txtVaiTro.setText("Giáo viên");
        panelTTTK.add(txtVaiTro, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        lbLop = new JLabel();
        lbLop.setText("Lớp");
        panelTTTK.add(lbLop, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtLop = new JTextField();
        txtLop.setDisabledTextColor(new Color(-16777216));
        txtLop.setEditable(false);
        txtLop.setEnabled(false);
        txtLop.setSelectionColor(new Color(-16777216));
        txtLop.setText("10A2");
        panelTTTK.add(txtLop, new GridConstraints(5, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        panelDMK = new JPanel();
        panelDMK.setLayout(new BorderLayout(0, 0));
        panelDMK.setBackground(new Color(-12387639));
        panelNoiDungCaiDat.add(panelDMK, "Card2");
        final JLabel label6 = new JLabel();
        label6.setText("Đổi mật khẩu");
        panelDMK.add(label6, BorderLayout.NORTH);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

    public static void main(String[] args) throws MalformedURLException, NotBoundException, RemoteException {
        // Khởi tạo giao diện
        JFrame frame = new JFrame("Giao diện cài đặt");
        TaiKhoanService taiKhoanService = (TaiKhoanService) Naming.lookup("rmi://localhost:8081/taiKhoanService");
        frame.setContentPane(new GiaoDienCaiDatTaiKhoan(taiKhoanService.finByID("angtrunglele@example.com")).$$$getRootComponent$$$());
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setSize(500, 300);
        frame.setVisible(true);
    }
}
