package gui;

import javax.swing.*;
import java.awt.*;

public class GiaoDienHocSinhDanhSachBaiThi extends JPanel {
    private JPanel panel1;
    private JTable tblDanhSachBaiThi;

    {
        $$$setupUI$$$();
    }

    public GiaoDienHocSinhDanhSachBaiThi() {
        // Không thêm logic tải dữ liệu hay sự kiện
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(10, 10));
        panel1.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));

        JPanel mainPanel = new JPanel();
        mainPanel.setLayout(new BorderLayout());

        JPanel panelDanhSach = new JPanel();
        panelDanhSach.setLayout(new BorderLayout());
        panelDanhSach.setBorder(BorderFactory.createTitledBorder("Danh sách bài thi"));

        String[] columns = {"Mã phiên", "Thời gian làm bài", "Điểm số", "Số câu đúng", "Số câu sai"};
        Object[][] data = {};
        tblDanhSachBaiThi = new JTable(data, columns);
        tblDanhSachBaiThi.setRowHeight(30);
        JScrollPane scrollPane = new JScrollPane(tblDanhSachBaiThi);
        panelDanhSach.add(scrollPane, BorderLayout.CENTER);

        mainPanel.add(panelDanhSach, BorderLayout.CENTER);

        panel1.add(mainPanel, BorderLayout.CENTER);

        setPreferredSize(new Dimension(1000, 600));
    }

    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            JFrame frame = new JFrame("Danh sách bài thi");
            frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            frame.setContentPane(new GiaoDienHocSinhDanhSachBaiThi().$$$getRootComponent$$$());
            frame.pack();
            frame.setSize(1000, 600);
            frame.setLocationRelativeTo(null);
            frame.setVisible(true);
        });
    }
}