package gui;

import com.intellij.uiDesigner.core.GridLayoutManager;
import entities.GiaoVien;
import entities.HocSinh;

import javax.swing.*;
import java.awt.*;

public class GiaoDienChinh extends JPanel {
    private JPanel panel1;
    public GiaoDienChinh(Object taiKhoan) {
        $$$setupUI$$$();

        panel1.setLayout(new BorderLayout());

        if (taiKhoan instanceof GiaoVien giaoVien) {
            panel1.add(new GiaoDienMenuGiaoVien(giaoVien).$$$getRootComponent$$$(), BorderLayout.CENTER);
        } else if (taiKhoan instanceof HocSinh hocSinh) {
            panel1.add(new GiaoDienMenuHocSinh(hocSinh).$$$getRootComponent$$$(), BorderLayout.CENTER);
        } else {
            panel1.add(new JLabel("Không xác định vai trò"), BorderLayout.CENTER);
        }
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));

    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }


}
