package gui;

import javax.swing.*;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import java.awt.*;

public class GiaoDienHocSinhXemKetQua extends JPanel {
    private JPanel panel1;
    private JLabel lblDiemSo;
    private JLabel lblSoCauDung;
    private JLabel lblSoCauSai;
    private JTable tblChiTiet;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    public GiaoDienHocSinhXemKetQua() {
        tblChiTiet.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                String ketQua = (String) table.getValueAt(row, 3); // Cột "Kết quả"
                if ("Đúng".equals(ketQua)) {
                    c.setBackground(new Color(144, 238, 144)); // Màu xanh nhạt cho câu đúng
                } else {
                    c.setBackground(new Color(255, 182, 193)); // Màu hồng nhạt cho câu sai
                }
                return c;
            }
        });


        TableColumn cauHoiColumn = tblChiTiet.getColumnModel().getColumn(0);
        cauHoiColumn.setPreferredWidth(300);
        tblChiTiet.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);

        cauHoiColumn.setCellRenderer(new TableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                JTextArea textArea = new JTextArea();
                textArea.setLineWrap(true);
                textArea.setWrapStyleWord(true);
                textArea.setText(value != null ? value.toString() : "");
                textArea.setEditable(false);
                textArea.setBackground(table.getBackground());

                // Tô màu dựa trên kết quả
                String ketQua = (String) table.getValueAt(row, 3);
                if ("Đúng".equals(ketQua)) {
                    textArea.setBackground(new Color(144, 238, 144));
                } else {
                    textArea.setBackground(new Color(255, 182, 193));
                }

                return textArea;
            }
        });
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(10, 10));
        panel1.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));

        // Panel chính với bố cục dọc
        JPanel mainPanel = new JPanel();
        mainPanel.setLayout(new BoxLayout(mainPanel, BoxLayout.Y_AXIS));

        // Phần thông tin tổng quan
        JPanel panelTongQuan = new JPanel();
        panelTongQuan.setLayout(new GridLayout(1, 3, 10, 10)); // Bố cục lưới 1 hàng, 3 cột
        panelTongQuan.setBorder(BorderFactory.createTitledBorder("Thông tin kết quả"));

        lblDiemSo = new JLabel("Điểm: 0/100");
        lblDiemSo.setFont(new Font("Arial", Font.BOLD, 16));
        lblDiemSo.setHorizontalAlignment(SwingConstants.CENTER);

        lblSoCauDung = new JLabel("Số câu đúng: 0");
        lblSoCauDung.setHorizontalAlignment(SwingConstants.CENTER);

        lblSoCauSai = new JLabel("Số câu sai: 0");
        lblSoCauSai.setHorizontalAlignment(SwingConstants.CENTER);

        panelTongQuan.add(lblDiemSo);
        panelTongQuan.add(lblSoCauDung);
        panelTongQuan.add(lblSoCauSai);

        // Phần chi tiết bài thi
        JPanel panelChiTiet = new JPanel();
        panelChiTiet.setLayout(new BorderLayout());
        panelChiTiet.setBorder(BorderFactory.createTitledBorder("Chi tiết bài thi"));

        String[] columns = {"Câu hỏi", "Đáp án chọn", "Đáp án đúng", "Kết quả"};
        Object[][] data = {};
        tblChiTiet = new JTable(data, columns);
        tblChiTiet.setRowHeight(40);
        JScrollPane scrollPane = new JScrollPane(tblChiTiet);
        panelChiTiet.add(scrollPane, BorderLayout.CENTER);

        // Thêm cả hai phần vào panel chính
        mainPanel.add(panelTongQuan);
        mainPanel.add(Box.createRigidArea(new Dimension(0, 10))); // Khoảng cách giữa hai phần
        mainPanel.add(panelChiTiet);


        panel1.add(mainPanel, BorderLayout.CENTER);

        setPreferredSize(new Dimension(1000, 600));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

    // Main để chạy thử
    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            JFrame frame = new JFrame("Kết quả bài thi");
            frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            frame.setContentPane(new GiaoDienHocSinhXemKetQua().$$$getRootComponent$$$());
            frame.pack();
            frame.setSize(1000, 600);
            frame.setLocationRelativeTo(null);
            frame.setVisible(true);
        });
    }
}