package gui;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.Locale;

public class GiaoDienMenuHocSinh extends JPanel {
    private JPanel panel1;
    private JPanel panelCaiDatTaiKhoan;
    private JPanel panelDanhSachBaiThi;
    private JPanel panelNoiDung;

    public GiaoDienMenuHocSinh() {
        panelCaiDatTaiKhoan.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                panelNoiDung.removeAll();
                panelNoiDung.add(new GiaoDienCaiDatTaiKhoan().$$$getRootComponent$$$());
                panelNoiDung.revalidate();
                panelNoiDung.repaint();

            }
        });
        panelDanhSachBaiThi.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                panelNoiDung.removeAll();
                panelNoiDung.add(new GiaoDienDanhSachBaiThi().$$$getRootComponent$$$());
                panelNoiDung.revalidate();
                panelNoiDung.repaint();

            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panel2.setBackground(new Color(-4725252));
        panel2.setPreferredSize(new Dimension(200, 20));
        panel1.add(panel2, BorderLayout.WEST);
        final JLabel label1 = new JLabel();
        Font label1Font = this.$$$getFont$$$(null, -1, 20, label1.getFont());
        if (label1Font != null) label1.setFont(label1Font);
        label1.setText("Học sinh");
        panel2.add(label1);
        panelDanhSachBaiThi = new JPanel();
        panelDanhSachBaiThi.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panelDanhSachBaiThi.setAlignmentX(0.0f);
        panelDanhSachBaiThi.setAlignmentY(0.0f);
        panelDanhSachBaiThi.setAutoscrolls(false);
        panelDanhSachBaiThi.setOpaque(true);
        panelDanhSachBaiThi.setPreferredSize(new Dimension(200, 30));
        panel2.add(panelDanhSachBaiThi);
        final JLabel label2 = new JLabel();
        label2.setText("Danh sách bài thi");
        panelDanhSachBaiThi.add(label2);
        panelCaiDatTaiKhoan = new JPanel();
        panelCaiDatTaiKhoan.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panelCaiDatTaiKhoan.setAlignmentX(0.0f);
        panelCaiDatTaiKhoan.setAlignmentY(0.0f);
        panelCaiDatTaiKhoan.setAutoscrolls(false);
        panelCaiDatTaiKhoan.setOpaque(true);
        panelCaiDatTaiKhoan.setPreferredSize(new Dimension(200, 30));
        panel2.add(panelCaiDatTaiKhoan);
        final JLabel label3 = new JLabel();
        label3.setText("Cài đặt tài khoản");
        panelCaiDatTaiKhoan.add(label3);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panel3.setAlignmentX(0.0f);
        panel3.setAlignmentY(0.0f);
        panel3.setAutoscrolls(false);
        panel3.setOpaque(true);
        panel3.setPreferredSize(new Dimension(200, 30));
        panel2.add(panel3);
        final JLabel label4 = new JLabel();
        label4.setText("Đăng xuất");
        panel3.add(label4);
        panelNoiDung = new JPanel();
        panelNoiDung.setLayout(new BorderLayout(0, 0));
        panel1.add(panelNoiDung, BorderLayout.CENTER);
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
    }
}
